### ISSUE TITLE
リソース（URL）設計

### ISSUE THREAD

**Issue by ai-24** [ai-24/word-warmup#26]
使用する技術は下記になります。
- バックエンド・・・Rails
- フロントエンド・・・Vue.js

SPAとMPAのハイブリッド、下記リストにSPAの表記がないものは全てMPAで作成する予定です。

また、プロトタイプでは英語表記、日本語表記切り替えられるようにするつもりでしたが、実装期間の関係でどちらか片方にすることを検討しています。もし当初の予定通り英語、日本語表記両方でいくのであれば、methodがGETの全てのpath名の先頭に日本語であれば/jaを、英語の際は/enをつけようと思っています。

## ユーザーアカウント操作
ユーザー認証ではGoogleでログインを使用します。
gem`omniauth-google-oauth2`を使用する予定です。

| Method | Path | Description | SPA | Redirect |
|:-----------|:------------|:------------|:------------|:------------|
| POST | /auth/:provider/callback | サインアップ・ログイン処理 |  | 1. サービス紹介ページからのログイン＝`/`、 2. 英単語・フレーズの新規作成ボタンからのログイン＝`/words_and_phrases/new?form=words_and_phrases` 、3. 英単語・フレーズの編集からのログイン＝`words_and_phrases/:id/edit?form=words_and_phrases` 、 4. 英単語・フレーズの削除からのログイン＝`/words_and_phrases/:id`、 5. クイズ終了後の最終結果画面でブックマークする機能とmemorised wordsリストにデータ移動させる機能からのログイン＝`/quiz/result(Words/phrasesタブ配下)` `/bookmarks/quiz/result(ブックマークタブ配下)` `/memorised_words/quiz/result(Memorised wordsタブ配下)` 6. ヘッダーからのログイン＝ログインボタンをクリックする前に表示されていた画面にリダイレクト |
| DELETE | /logout | ログアウト処理 |  | `/` |
| DELETE | /me | アカウントの削除処理 |  | `/welcome` |

## サービス紹介ページ
| Method | Path | Description | SPA | Redirect |
|:-----------|:------------|:------------|:------------|:------------|
| GET | /welcome | サービス紹介ページを表示 |

## メインページ
| Method | Path | Description | SPA | Redirect |
|:-----------|:------------|:------------|:------------|:------------|
| GET | / | Words/Phrasesタブ配下（デフォルト表示）の英単語・フレーズのリストを表示 |  |
| GET | /bookmarked_words_and_phrases | Bookmarkタブ配下の英単語・フレーズのリストを表示 | |
| GET | /memorised_words_and_phrases | Memorised wordsタブ配下の英単語・フレーズのリストを表示 |  |

## クイズ
クイズの問題、回答入力画面と、クイズの問題、回答入力画面でサブミットした後に表示される正解不正解の結果を表示する画面はクイズが終了するまで交互に繰り返されますが、回答入力後それぞれの問題に戻る必要や、次の問題に進んだ際に前回の問題の正誤判定画面に戻る必要はないのでidや別のURLを付けなくても問題ないかと判断し下記のようにしました。
~~ただクイズの回答登録処理後のリダイレクトが/quizとなるのであまり自信はないです。~~

| Method | Path | Description | SPA | Redirect |
|:-----------|:------------|:------------|:------------|:------------|
| GET | /quiz | Words/Phrasesタブ（デフォルト表示）配下で行うクイズの問題、回答入力画面、最終結果画面を表示 | SPA |
| GET | /bookmarked_words_and_phrases/quiz | Bookmarkタブ配下で行うクイズの問題、回答入力画面、最終結果画面を表示 | SPA |
| GET | /memorised_words_and_phrases/quiz | Memorised wordsタブ配下で行うクイズの問題、回答入力画面、最終結果画面を表示 | SPA |

### API(JSONを使用)
| Method | Path | Description | HTTP request | HTTP response status codes | 
|:-----------|:------------|:------------|:------------|:------------|
| GET | /api/quiz | Words/Phrasesタブ（デフォルト表示）配下で行うクイズの問題と答えをRailsから取得 |  |
| GET | /api/bookmarked_words_and_phrases/quiz | Bookmarkタブ配下で行うクイズの問題と答えをRailsから取得 |  |
| POST | /api/bookmarked_words_and_phrases | クイズの最終結果画面で英単語・フレーズをBookmarkに保存 | { word_and_phrase_ids: [ :id,  :id... ] } | [ブックマークに保存が成功した時: 204、ログイン状態でないためリクエストする権限がない時: 401 |
| GET | /api/memorised_words_and_phrases/quiz | Memorised wordsタブ配下で行うクイズの問題と答えをRailsから取得 |  |
| POST | /api/memorised_words_and_phrases | クイズの最終結果画面で英単語・フレーズをMemorised wordsリストに保存 | { word_and_phrase_ids: [ :id,  :id... ] } | Memorised wordリストに保存が成功した時: 204、ログイン状態でないためリクエストする権限がない時: 401 |

## 英単語・フレーズの詳細画面、新規作成、編集、削除
| Method | Path | Description | SPA | Redirect |
|:-----------|:------------|:------------|:------------|:------------|
| GET | /words_and_phrases/:id | 英単語・フレーズのデータの詳細画面を表示 | SPA |
| GET | /words_and_phrases/new | 英単語・フレーズを新規登録する画面（画面遷移（ブラウザのリロード)なしが4ページ）を表示 | SPA |
| POST | /words_and_phrases | 英単語・フレーズの新規登録処理 |
| GET | /words_and_phrases/:id/edit | 英単語・フレーズを編集する（画面遷移（ブラウザのリロード)なしが4ページ）を表示 | SPA |
| PUT | /words_and_phrases/:id | 英単語・フレーズの編集処理 |
| DELETE | /words_and_phrases/:id | 英単語・フレーズの削除処理 |

~~**新規作成・編集ページの補足**~~
~~ページが複数となるため、パラメーターを使って表現しようと思っています。~~
~~下記が検討しているパラメーターです。~~
~~- form1(単語とフレーズを登録する）・・・`?form=words_and_phrases`~~
~~- form2（意味・例文を登録する）・・・`?form=explanation1`数字の部分には、 form1で登録された単語・フレーズ数に合わせて表示させる~~
~~- form4(任意入力のメモとタグ）・・・`?form=optional`~~

**Vueでデータを保持して使用するのでパラメーターは不要。**

## その他
| Method | Path | Description | SPA | Redirect |
|:-----------|:------------|:------------|:------------|:------------|
| GET | /terms_of_service | 利用規約を表示 |  |  |
| GET | /privacy_policy | プライバシーポリシーを表示 |  |  |

**Comment by ai-24** [comment]
| Method | Path | Description |
|:-----------|------------:|:------------|
|  |  | サービス紹介のホームページを表示する |
|  |  | サービス自体のメインページでWords/Phrasesタブ配下（デフォルト表示）の英単語・フレーズのリストを表示する |
|  |  | サービス自体のメインページでBookmarkタブ配下の英単語・フレーズのリストを表示する |
|  |  | サービス自体のメインページでMemorised wordsタブ配下の英単語・フレーズのリストを表示する |
|  |  | 英単語・フレーズのデータの詳細画面を表示する |
|  |  | クイズ画面を表示する |
|  |  | Words/phrasesリストから行ったクイズの最終結果画面を表示する |
|  |  | Bookmarkから行ったクイズの最終結果画面を表示する |
|  |  | Memorised wordsリストから行ったクイズの最終結果画面を表示する |
|  |  | 英単語・フレーズのデータを新規登録する |
|  |  | 英単語・フレーズのデータを編集する |
|  |  | 英単語・フレーズのデータを削除する |

**Comment by cafedomancer** [comment]
## 全般

- Rails のパスのデフォルトは snake_case です。snake_case ではなく kebab-case を採用している理由はなにかありますか？
- SPA と MPA の分類がリソース設計とどう関係あるのか分かりませんでした。どのような意図があって SPA と MPA の分類を行っていますか？
- `/current-user` というプリフィックスがどういう意図を持って付けられているのか分かりませんでした。これはどういう意図で付けられていますか？

## ユーザーアカウント操作

- ログイン後・ログアウト後・アカウント削除後のリダイレクト先のページに関する情報が URL に含まれていないようなので、実現の見通しが付きませんでした。そもそもこれはどのような仕組みで実現する予定ですか？

## サービス紹介ページ

- `/welcom` は `/welcome` の間違いかなと思います

## 英単語・フレーズの詳細画面、新規作成、編集、削除

- ID は `: word_and_phrase_id` ではなく単に `:id` でよいと思います
- 新規作成ページ・編集ページが複数になるとして、ページごとのデータの永続化もしくはページ間でのデータの受け渡しはどのような仕組みで行う予定ですか？

**Comment by ai-24** [comment]
@cafedomancer 
レビューありがとうございます！

## 全般
> Rails のパスのデフォルトは snake_case です。snake_case ではなく kebab-case を採用している理由はなにかありますか？

kebab-case を採用した理由は、URLに関する記事を探していた際に`_`よりも`-`の使用をSEOの関係で推奨されている記事を目にし、Google Developersに目を通すと同じようにURLには`_`よりも`-`を使うことを推奨されていたこと、またいろんなサイトを見てみた際にkebab-caseが使用されていることが多かったためです。ただRails のパスのデフォルトは snake_case ということが抜けていました。Googleは公式で`-`を推奨していますが、`_`を使用したからといってSEOに問題があるわけでもなさそうなので、パスはRailsで作成することを踏まえsnake_caseに変更しようと思います。
変更はリソース設計に反映させております。

> SPA と MPA の分類がリソース設計とどう関係あるのか分かりませんでした。どのような意図があって SPA と MPA の分類を行っていますか？

MPAは画面遷移する度にHTTPリクエストが行われるので、画面の表示が変わる毎に異なるパスが必要だと認識しています。
一方SPAはHTTPリクエストを行うのは初回のリクエストの時だけだと認識しているので、画面遷移があっても異なるパスは必要ないと考えました。そのため、SPAとMPAの分類があった方が良いかと思い分類しました。

> `/current-user` というプリフィックスがどういう意図を持って付けられているのか分かりませんでした。これはどういう意図で付けられていますか？

FBCのダッシュボードの中のブックマークを参考に、ログインしているユーザーが所有するブックマークや覚えた単語という意図でつけました。

## ユーザーアカウント操作
> ログイン後・ログアウト後・アカウント削除後のリダイレクト先のページに関する情報が URL に含まれていないようなので、実現の見通しが付きませんでした。そもそもこれはどのような仕組みで実現する予定ですか？

サインアップ・ログイン処理は先ほど口頭でご教示いただいた、フレンドリーフォワーディングで実装しようと思います。
ログアウト、アカウント削除に関してはアドバイスいただいたようにリダイレクト先を１つに絞りました。

## サービス紹介ページ
> `/welcom` は `/welcome` の間違いかなと思います

大変失礼いたしました。修正いたしました。

## 英単語・フレーズの詳細画面、新規作成、編集、削除
> ID は : word_and_phrase_id ではなく単に :id でよいと思います

確かに`rails routes`で表示されるものも:idでした。
ご指摘ありがとうございます。
修正いたしました。

> 新規作成ページ・編集ページが複数になるとして、ページごとのデータの永続化もしくはページ間でのデータの受け渡しはどのような仕組みで行う予定ですか？

複数に渡る全ての入力フォームをVueの1つのSFCで作成しようと思っており、`v-show`を使って表示させるページを変更する予定です。
入力フォームに入力されたデータを`v-model`を使ってVueで保持するようにしようと思っています。

**Comment by cafedomancer** [comment]
## 全般

> > `/current-user` というプリフィックスがどういう意図を持って付けられているのか分かりませんでした。これはどういう意図で付けられていますか？

> FBC のダッシュボードの中のブックマークを参考に、ログインしているユーザーが所有するブックマークや覚えた単語という意図でつけました。

- `/current_user` というプリフィックスはいらないかなーと思います。ブックマークや覚えた単語がユーザーに固有であることは自明で、このプリフィックスを付けることによって情報が特に増えていないことと、一般的なプリフィックスではないと思うからです。

## メインページ

- 確認なのですが、memorised は American English ではなく British English であるという認識で大丈夫ですか？
- ブックマークや覚えたXXXの対象が `words_and_phrases` なので、以下のように名前を揃えてあげると統一感が出るんじゃないかなーと思いました。
  - (words_and_phrases), bookmarked_words_and_phrases, memorised_words_and_phrases
  - (words_and_phrases が長いと感じるなら words_and_phrases 自体を別の名前にするのもアリかも)

## クイズ

- 今どの英単語・フレーズのクイズを解いているかという情報が URL には含まれていないのですが、この情報はどこにどのように保持する予定ですか？
- 回答入力画面でサブミットすると、画面は変わらずに回答が表示される感じでしょうか？ それとも通常の HTTP の通信が行われて画面遷移が発生した上で回答が表示される感じでしょうか？
- クイズの回答入力画面の表示や最終結果画面の表示を Rails の規定のアクションに当てはめると、それぞれ new や show のように考えることができそうな気がしました。`/quiz/result` のようなルーティングは、Rails のデフォルトの RESTful なルーティングからは外れたものになってしまうので、規定のアクションに当てはめてルーティングを考えられないか見直してみてください。

## 英単語・フレーズの詳細画面、新規作成、編集、削除

- フォームのクエリパラメータはどのような目的で付与していますか？ (= これがあるとどんな嬉しいことがありますか？)

**Comment by ai-24** [comment]
@cafedomancer 
レビューありがとうございます！

## 全般
> `/current_user` というプリフィックスはいらないかなーと思います。ブックマークや覚えた単語がユーザーに固有であることは自明で、このプリフィックスを付けることによって情報が特に増えていないことと、一般的なプリフィックスではないと思うからです。

なるほど、おっしゃる通りです。`/current_user`は削除いたしました。

## メインページ
> 確認なのですが、memorised は American English ではなく British English であるという認識で大丈夫ですか？

はい！用意する初期データはBritish Englishをベースにする予定なので、それに合わせてアプリで使用するものはBritish Englishにしようと思っています。

> ブックマークや覚えたXXXの対象が words_and_phrases なので、以下のように名前を揃えてあげると統一感が出るんじゃないかなーと思いました。
- (words_and_phrases), bookmarked_words_and_phrases, memorised_words_and_phrases
- (words_and_phrases が長いと感じるなら words_and_phrases 自体を別の名前にするのもアリかも)

確かに統一感出ますね！ bookmarked_words_and_phrases, memorised_words_and_phrasesに変更しました。
ただここで`/`をどうするか迷いました。words_and_phrasesをつけた方が統一感は出ると思うのですが、デフォルトのリストを`/`にしたかったので、words_and_phrasesはつけませんでした。違和感などありますでしょうか？

## クイズ
> 今どの英単語・フレーズのクイズを解いているかという情報が URL には含まれていないのですが、この情報はどこにどのように保持する予定ですか？

Vueにデータを持たせようと思っているので、クイズ開始から、クイズの最終結果画面を経て他の画面に遷移されるまでの間Vueのdataとして保持する予定です。
クイズを実行中は前の画面などに戻ることを想定していなかったので、クエリをつけることは検討していなかったのですが、もし何か懸念点があってつけた方が良さそうでしたら、質問と回答入力フォームが表示される画面では`?page=question1(今解いている問題が何番目の問題なのか数字で表す）`、正解不正解が表示される画面は`?page=answer1(今解いている問題が何番目の問題なのか数字で表す）`としようかなと思います。クエリをつけるのであれば前ページに戻るボタンを設置するとタイポの時に戻って修正出来て良いのかなと思ったりしています。

> 回答入力画面でサブミットすると、画面は変わらずに回答が表示される感じでしょうか？ それとも通常の HTTP の通信が行われて画面遷移が発生した上で回答が表示される感じでしょうか？

クイズを行う際は画面がさくさく動いて欲しいので、通常のHTTPの通信は行いません。画面は変わらず回答が表示されます。
分かりにくくて申し訳ありませんでした。
ここで気づいたのですが、Vueにデータを保持させるのであればPOSTの処理である下記のような設計は不要なのでは？と思いました。
| Method | Path | Description | SPA | Redirect |
|:-----------|:------------|:------------|:------------|:------------|
| POST | /quiz | クイズの回答を登録処理 |  | /quiz |

よってこのような設計になっているところを全て削除しました。

> クイズの回答入力画面の表示や最終結果画面の表示を Rails の規定のアクションに当てはめると、それぞれ new や show のように考えることができそうな気がしました。/quiz/result のようなルーティングは、Rails のデフォルトの RESTful なルーティングからは外れたものになってしまうので、規定のアクションに当てはめてルーティングを考えられないか見直してみてください。

クイズの問題、回答入力画面の表示を`/quizzes/new`のように修正しました。
ここで少し気になったのが、正解不正解を表示する画面のURLは変更せずにいこうと思っているのですが、この入力できるフォームがないページ（この画面ではクイズの問題、回答入力画面で入力フォームだった部分をフォームではなくただの表示にしようと思っています）で`new?page=answer1`としても問題ないでしょうか？
クイズの最終結果画面の表示をRailsのshowアクションに当てはめて`quizzes/:id`のようにしようかと思ったのですが、昨日口頭でご教示いただいた際にQuizテーブルを削除したのでidをどこから取ってくるか迷いました。迷った結果`quizzes/new?page=result`にしようかと思ったのですがいかがでしょうか？

## 英単語・フレーズの詳細画面、新規作成、編集、削除
> フォームのクエリパラメータはどのような目的で付与していますか？ (= これがあるとどんな嬉しいことがありますか？)

クエリパラメータがあることで、`次へ`や`戻る`ボタンでフォームを別のフォームに移動できたり、ナビゲーションから選択してフォームを別のフォームに移動できたりすると思っています。
一旦１つの表示されているフォームの入力を終えて次のフォームに行った際に、後から前のフォームに戻って内容を追加・修正出来たりすることがメリットかなと思っています。認識間違いしている部分などあればご指摘お願いします。

**Comment by cafedomancer** [comment]
> ただここで/をどうするか迷いました。words_and_phrasesをつけた方が統一感は出ると思うのですが、デフォルトのリストを/にしたかったので、words_and_phrasesはつけませんでした。違和感などありますでしょうか？

これでよいと思います！

> Vueにデータを持たせようと思っているので、クイズ開始から、クイズの最終結果画面を経て他の画面に遷移されるまでの間Vueのdataとして保持する予定です。

Rails から Vue へのデータの受け渡しはどのように行う予定ですか？ 場合によって API エンドポイントを用意しないといけない気がしました。

> クイズを実行中は前の画面などに戻ることを想定していなかったので、クエリをつけることは検討していなかったのですが、もし何か懸念点があってつけた方が良さそうでしたら、質問と回答入力フォームが表示される画面では?page=question1(今解いている問題が何番目の問題なのか数字で表す）、正解不正解が表示される画面は?page=answer1(今解いている問題が何番目の問題なのか数字で表す）としようかなと思います。クエリをつけるのであれば前ページに戻るボタンを設置するとタイポの時に戻って修正出来て良いのかなと思ったりしています。

クエリパラメータは特にいらないかなーと思います。ブラウザの戻るボタンで前ページに戻る機能を実現するのだとすると、Vue.js 上の動作に合わせて History API を操作する必要が出てきます。ただ、これを Rails と組み合わせると、Vue.js で管理している URL と Rails で管理している URL が競合して面倒なので、今回のケースではこの機能を実現するのはオススメしません。

> ここで気づいたのですが、Vueにデータを保持させるのであればPOSTの処理である下記のような設計は不要なのでは？と思いました。
> よってこのような設計になっているところを全て削除しました。

いいと思います :ok_person:

> クイズの最終結果画面の表示をRailsのshowアクションに当てはめてquizzes/:idのようにしようかと思ったのですが、昨日口頭でご教示いただいた際にQuizテーブルを削除したのでidをどこから取ってくるか迷いました。迷った結果quizzes/new?page=resultにしようかと思ったのですがいかがでしょうか？

結果の表示も Vue.js 側で画面遷移をせずに行うと思うので、回答画面も合わせて `/quiz` や `/quizzes` でいいんじゃないかなーと思いました。

> クエリパラメータがあることで、次へや戻るボタンでフォームを別のフォームに移動できたり、ナビゲーションから選択してフォームを別のフォームに移動できたりすると思っています。
一旦１つの表示されているフォームの入力を終えて次のフォームに行った際に、後から前のフォームに戻って内容を追加・修正出来たりすることがメリットかなと思っています。認識間違いしている部分などあればご指摘お願いします。

この画面は Vue.js で作成するとのことだったので、Vue.js の中でで戻る・進むができるのはいいと思います。その場合、クエリパラメータは特に必要ないかなーと思います。ブラウザの戻る・進むボタンでも動くようにするのは、前述のとおり、今回のケースではオススメしません。

* * *

以下、リソース設計のフィードバックです。

## クイズ

- 上記のコメントに合わせて酒精をお願いします！
- 最終結果画面が表示されたタイミングで、特定の words_and_phrases を Bookmark や Memorised words に移動？保存？するための URL が必要になる気がしました。実現方法と合わせて、どんな URL が必要かを考えてみてください。

**Comment by ai-24** [comment]
@cafedomancer 
レビューありがとうございます！
下記修正いたしました。
ご確認よろしくお願いいたします🙇‍♀️

## クイズ
> Rails から Vue へのデータの受け渡しはどのように行う予定ですか？ 場合によって API エンドポイントを用意しないといけない気がしました。

ご指摘ありがとうございます！
Rails APIを使う予定なのでAPI エンドポイントを`クイズ`、`英単語・フレーズの詳細画面、新規作成、編集、削除`で用意致しました。

> クエリパラメータは特にいらないかなーと思います。ブラウザの戻るボタンで前ページに戻る機能を実現するのだとすると、Vue.js 上の動作に合わせて History API を操作する必要が出てきます。ただ、これを Rails と組み合わせると、Vue.js で管理している URL と Rails で管理している URL が競合して面倒なので、今回のケースではこの機能を実現するのはオススメしません。

なるほどです。ご教示いただきありがとうございます！

> 結果の表示も Vue.js 側で画面遷移をせずに行うと思うので、回答画面も合わせて /quiz や /quizzes でいいんじゃないかなーと思いました。

`/quiz`に修正しました。

> 最終結果画面が表示されたタイミングで、特定の words_and_phrases を Bookmark や Memorised words に移動？保存？するための URL が必要になる気がしました。実現方法と合わせて、どんな URL が必要かを考えてみてください。

おっしゃる通りでした。クイズのAPIの部分に追加いたしました。

## 英単語・フレーズの詳細画面、新規作成、編集、削除
> この画面は Vue.js で作成するとのことだったので、Vue.js の中でで戻る・進むができるのはいいと思います。その場合、クエリパラメータは特に必要ないかなーと思います。ブラウザの戻る・進むボタンでも動くようにするのは、前述のとおり、今回のケースではオススメしません。

かしこまりました。クエリパラメータは削除いたしました。

**Comment by cafedomancer** [comment]
## 全般

API エンドポイントはたぶんリダイレクトしないはずなので、リダイレクトの項目は記入しなくてよいと思います。この提出物に書く必要はないのですが (もちろん書いてもらっても OK) 、リクエスト時にどのようなパラメータを受け取るかや、リクエストの成功時・失敗時にどのようなステータスコードやレスポンスを返すか、などについて実装の前に考えておくとよいと思います。

## クイズ

> `DELETE api/bookmarked_words_and_phrases/:id`
> クイズの最終結果画面でBookmarkに保存されていた英単語・フレーズをMemorised wordsリストに保存先を変更する際にBookmarkから削除する	

これは `POST /api/memorised_words_and_phrases` 相当の処理なんじゃないかなーと思いました。その処理の中で Bookmark に保存されている英単語・フレーズがあれば、その中間レコードを削除するというふうにするといいんじゃないかなと思います。

> `DELETE /api/memorised_words_and_phrases/:id`
> クイズの最終結果画面でMemorised wordsリストに保存されている英単語・フレーズをBookmarkに保存先を変更する際にMemorised wordsリストから削除する

こちらも上記と同様です。

**Comment by ai-24** [comment]
@cafedomancer 
レビューありがとうございます。
修正と質問をさせていただきました。
ご確認よろしくお願いいたします。

## 全般
> API エンドポイントはたぶんリダイレクトしないはずなので、リダイレクトの項目は記入しなくてよいと思います。

リダイレクトの項目を削除しました。

> リクエストの成功時・失敗時にどのようなステータスコードやレスポンスを返すか、などについて実装の前に考えておくとよいと思います。

なるほどです。知識不足で申し訳ないのですがこの部分について質問させてください。
事前にこれらの情報を検討しておくのは、実装した際にlogと照らし合わせて意図したステータスコードやレスポンスが返って来ているかを確認したり、リクエスト失敗時に表示させるエラー画面を作るために事前に検討しておいた方がいいということでしょうか？
また例えばHTTPメソッドPOSTでリクエストをおくった際に(検討する際にはもっと具体的に落とし込む必要はありますが）、成功時であれば`302 Found`が返りリダイレクトされた後に`200 OK`が返るという事を１つ１つのアクションに当てはめて考えておくという認識であっていますでしょうか？

## クイズ
> これは POST /api/memorised_words_and_phrases 相当の処理なんじゃないかなーと思いました。その処理の中で Bookmark に保存されている英単語・フレーズがあれば、その中間レコードを削除するというふうにするといいんじゃないかなと思います。

ユーザーが行う１つの動作でリクエストを２回投げるのは確かに変でした。
`DELETE api/bookmarked_words_and_phrases/:id` `DELETE /api/memorised_words_and_phrases/:id`は削除いたしました。

**Comment by cafedomancer** [comment]
確認しました。OK そうです！

> 事前にこれらの情報を検討しておくのは、実装した際にlogと照らし合わせて意図したステータスコードやレスポンスが返って来ているかを確認したり、リクエスト失敗時に表示させるエラー画面を作るために事前に検討しておいた方がいいということでしょうか？
また例えばHTTPメソッドPOSTでリクエストをおくった際に(検討する際にはもっと具体的に落とし込む必要はありますが）、成功時であれば302 Foundが返りリダイレクトされた後に200 OKが返るという事を１つ１つのアクションに当てはめて考えておくという認識であっていますでしょうか？

まず、これは API エンドポイントに限った話です。HTML を表示するルーティングについては Rails が大体よしなにやってくれるので特に考える必要はありません。API エンドポイントについては、リクエストやレスポンスのデータをどのようなフォーマットで扱うかや、リクエストの成功時や失敗時どのようなステータスコードを返すかなどを自分で考えて決めて実装していく必要があります。これらの設計を予めやっておかないと、いざ実装の段になった際に何をどうすればいいのか分からなくなってしまうのでは、と思ったのでアドバイスしました。

**Comment by ai-24** [comment]
@cafedomancer 
レビューありがとうございます！

> まず、これは API エンドポイントに限った話です。HTML を表示するルーティングについては Rails が大体よしなにやってくれるので特に考える必要はありません。API エンドポイントについては、リクエストやレスポンスのデータをどのようなフォーマットで扱うかや、リクエストの成功時や失敗時どのようなステータスコードを返すかなどを自分で考えて決めて実装していく必要があります。これらの設計を予めやっておかないと、いざ実装の段になった際に何をどうすればいいのか分からなくなってしまうのでは、と思ったのでアドバイスしました。

なるほどです！！アドバイスありがとうございます！勉強になります。
APIのコントローラーにリクエストの成功時や失敗時に返すステータスコードを自分で書くのですね！
チーム開発ではすでに設定されていたので自分で考える必要があると気づけませんでした。
確かに事前に考えておかないと迷ってしまいそうです。

いただいたアドバイスを元に検討してみました。
お手隙の時にご確認いただけますでしょうか？🙇‍♀️

まずフォーマットはJSONを使用します。
取得するパラメーターの内容とリクエストの成功時や失敗時どのようなステータスコードを返すかをAPIのリスト部分に記載させていただきました。
GETにステータスコードを記載しなかった理由はブートキャンプのAPIコントローラーを見に行くとindex、show アクションではステータスコードの記載が見当たらなかった事を参考にしたためです。

認識が間違っている部分などありましたらご指摘お願いします🙏

**Comment by cafedomancer** [comment]
もう少し細かく考える必要がありそうです。例を 1 つ示すので参考にしてみてください。

- `POST /api/bookmarked_words_and_phrases`
  - リクエスト: たぶん複数の英単語・フレーズをブックマークに追加することになるので、英単語・フレーズの識別子 (まあ ID かな？) を複数受け取る必要があります。まずデータをどこに含めるのか考える必要があります。query string なのか request body なのか。query string なら `word_and_phrase_ids[]=123&word_and_phrase_ids[]=456` のような形式や `word_and_phrase_ids=123,456` のような形式などいくつかバリエーションがあります。request body に JSON として含めるのなら `{ word_and_phrase_ids: [123, 456] }` のようにすれば良さそうです。
  - レスポンス: ステータースコードは、データの追加や変更に成功したとき、バリデーションなどに引っかかって失敗したとき、ログイン状態でないためリクエストする権限がそもそもないとき、などに分けて考える必要があります。この例で言えば、それぞれ 201 (もしくは 200), 422 (もしくは 400), 401 となるでしょう。response body として返すものがないのであれば、成功時に 204 を返すのでもよいかもしれません。response body は、画面で使うデータがあればそれに応じた JSON を含めるとよいでしょう。なければ何も含めずにステータスコードを返すだけでよいと思います。

英単語・フレーズの詳細画面、新規作成、編集、削除 の API のところって前もありましたか？ ここは API ではなく普通のリクエスト・レスポンスで処理すればいいのではと思いました。それぞれの処理が終わったあとに画面遷移が発生すると思うのですが、API でデータをやり取りした上で画面遷移を発生させるのは面倒だと思うからです (常にそうなわけではありません。この画面に限った話です) 。

**Comment by ai-24** [comment]
@cafedomancer 
ご教示いただきありがとうございます！
クイズのAPIの部分を修正いたしましたのでご確認よろしくお願いいたします。

> 英単語・フレーズの詳細画面、新規作成、編集、削除 の API のところって前もありましたか？

下記で英単語・フレーズの詳細画面、新規作成、編集、削除 の APIを設計しておりました。
クイズの部分で書いていたので分かりにくかったと思います。
申し訳ありませんでした。以後気をつけます。
https://github.com/ai-24/word-warmup/issues/26#issuecomment-1384852400

> ここは API ではなく普通のリクエスト・レスポンスで処理すればいいのではと思いました。

なるほどです。もしかすると私のAPIに対する認識が間違っているかもしれないので確認させてください。
VueのSFCを使って実装する際にはデータをVueで処理または受け取り、APIエンドポイントを使ってそのデータをRailsに渡す作業が必要だと認識しております。
英単語・フレーズの登録フォームが複数ページに渡るので、そのページの切り替えをスムーズに行うために英単語・フレーズの登録フォームをSFCで作成しようと思っていました。そのため、APIエンドポイントを設計したのですが、英単語・フレーズの詳細画面、新規作成、編集、削除はRailsで実装した方がスムーズということでしょうか？
またはVueでSFCを実装する際にAPIエンドポイントが必要という認識がずれていますか？

**Comment by cafedomancer** [comment]
Vue を使用する = API が必要になる、ではないです。Rails と Vue のデータの受け渡し方には、方向によってそれぞれ以下のような方法があります。

- Rails から Vue
  - Rails のビューで JSON 相当の文字列をテンプレートに埋め込んで、Vue のコンポーネントをレンダリングするときにその JSON 文字列を parse して Vue のデータとして使用する
  - Rails 側で用意した API に Vue からアクセスする
- Vue から Rails
  - フォームを作って submit して普通に POST リクエストを投げる (検索のときなどは GET リクエストが使われる)
  - Rails 側で用意した API に、fetch 関数などを使って Vue から非同期なリクエストを投げる

Rails から Vue へのデータの渡し方に関しては、今回はどちらでやってもよいかなーと思います。Vue から Rails へのデータの渡し方に関しては、画面遷移が絡むならフォームを作って普通に POST するほうが簡単かなと思います。ただし、フォームの送信時にはバリデーションエラーが起きない = Vue 側でバリデーションが行われている、という状況に限ります。サーバー側でないと判断できないようなバリデーションエラーが絡む場合は、普通の POST リクエストでやるとバリデーションエラーがあったときに Vue の画面に戻すのが大変なので、画面遷移も含めて Vue でやって API を叩いたほうが楽だと思います。

上記から、英単語・フレーズの操作画面については、Vue -> Rails のデータの渡し方は普通のフォームでやるのが簡単なんじゃないかなと思っていました。ちなみにクイズのところは保存部分を API にしてしまいましが、画面の Save を押したあとは何が起きるんですっけ？ 画面遷移が絡むなら、こちらも API ではなく普通の POST リクエストを受け付けるルーティングしたほうが楽かもしれません。

**Comment by cafedomancer** [comment]
おお、よさそうです。OK です！ 🙆

**Comment by ai-24** [comment]
@cafedomancer 
レビューありがとうございました！
たくさんご教示いただき勉強になりました🙇‍♀️

**Comment by ai-24** [comment]
@cafedomancer 
昨日の進捗報告会で駒形さんがおっしゃられていた[ 梅本さんから頂いたコメント ](https://github.com/ai-24/word-warmup/issues/26#issuecomment-1374721526)にある

> (words_and_phrases が長いと感じるなら words_and_phrases自体を別の名前にするのもアリかも)

の`words_and_phrases`を修正しようかと思っています。（今丁度このテーブル周りの実装に取り組んでいて、DBとモデルを繋ぐのに`words_and_phrases`だと一工夫入りそうだと感じていたので、修正するなら今がいいと思いました。）
再検討した結果、`expressions`が一番いいような気がしているのですが、梅本さんの意見をお伺いさせていただきたいです。

また`expressions`に変更するとなると変更箇所は
- メインページ
    - `/bookmarked_words_and_phrases`を`/bookmarked_expressions`に変更
    - `/memorised_words_and_phrases`を`/memorised_expressions`に変更
- クイズ
    - `/bookmarked_words_and_phrases/quiz`を`/bookmarked_expressions/quiz`に変更
    - `/memorised_words_and_phrases/quiz`を`/memorised_expressions/quiz`に変更
    - `/api/bookmarked_words_and_phrases/quiz`を`/api/bookmarked_expressions/quiz`に変更
    - `/api/bookmarked_words_and_phrases`を`/api/bookmarked_expressions`に変更
    - `/api/memorised_words_and_phrases/quiz`を`/api/memorised_expressions/quiz`に変更
    - /api/memorised_words_and_phrases`を`/api/memorised_expressions`に変更
- 英単語・フレーズの詳細画面、新規作成、編集、削除
`words_and_phrases`部分を全て`expressions`に変更
- [ DB設計 ](https://github.com/ai-24/word-warmup/issues/4)
    - `words_and_phrases`テーブル名を`expressions`に変更し、この外部キーが入っているところの名前も合わせて`expression_id`に変更
    -  `word_and_phrase_items`テーブル名を`expression_items`に変更し、この外部キーが入っているところの名前も合わせて`expression_item_id`に変更

で大丈夫でしょうか？
ご確認よろしくお願いいたします🙇‍♀️

**Comment by cafedomancer** [comment]
expressions は悪くなさそうですね。変更箇所もそれでよいと思います！

**Comment by ai-24** [comment]
@cafedomancer 
早速ご確認ありがとうございます🙇‍♀️
ではこれで再度進めてまいります！
