### ISSUE TITLE
DB設計をする

### ISSUE THREAD

**Issue by ai-24** [ai-24/word-warmup#4]
### [プラットフォーム]
Fly.io

### [ DB ]
Fly Postgres

### [バックエンド]
Rails

### [フロントエンド]
Vue.js

# ER図

<img width="530" alt="image" src="https://user-images.githubusercontent.com/76685187/214011372-e36eb6ed-481a-4642-a39e-5473544595ec.png">

<details><summary>5回目</summary>
<img width="553" alt="image" src="https://user-images.githubusercontent.com/76685187/213844048-cca6df14-dd72-40a7-a0a0-1a830d2bf46d.png">
</details>

<details><summary>4回目</summary>
<img width="530" alt="image" src="https://user-images.githubusercontent.com/76685187/212847213-e48ac917-b629-4cc5-bc92-35c68fb4937d.png">
</details>

<details><summary>3回目</summary>
<img width="527" alt="image" src="https://user-images.githubusercontent.com/76685187/211516011-41faa8b7-e1f6-43ba-9732-517b65251309.png">
</details>

<details><summary>2回目</summary>
<img width="540" alt="image" src="https://user-images.githubusercontent.com/76685187/211133797-e381bade-61e8-4000-8b40-7c5e3165884a.png">
</details>

<details><summary>１回目</summary>
<img width="605" alt="image" src="https://user-images.githubusercontent.com/76685187/208959557-076f27f2-023f-417c-9553-61bf07534bfb.png">
</details>

# テーブル・カラムの説明とデータ型・制約
## User
[ テーブルの説明 ]
サインアップしたユーザーのデータ。
| カラム名 | データ型 | 制約 | データの詳細 |
|:-----------|:------------|:------------|:------------|
| uid | string | NOT NULL | Auth Hashのuid | 
| name | string | NOT NULL | ユーザー名（Auth Hashのname） |

ユーザー認証は`omniauth-google-oauth2`を使用します。

## Bookmarking
[ テーブルの説明 ]
ユーザー登録後に利用できる機能である、ブックマークのタブ配下に表示されるブックマークされた英単語・フレーズのデータのリスト。
| カラム名 | データ型 | 制約 | データの詳細 |
|:-----------|:------------|:------------|:------------|
| user_id | integer | NOT NULL | このリストを持っているユーザーのID |
| word_and_phrase_id | integer | NOT NULL | ブックマークリストに属する英単語・フレーズのID |

## Memorising
[ テーブルの説明 ]
ユーザー登録後に利用できる機能である、覚えた単語・フレーズのリスト。Memorised wordsタブ配下に表示される。
| カラム名 | データ型 | 制約 | データの詳細 |
|:-----------|:------------|:------------|:------------|
| user_id | integer | NOT NULL | このリストを持っているユーザーのID |
| word_and_phrase_id | integer | NOT NULL | Memorised wordsリストに属する英単語・フレーズのID |

## WordAndPhrase
[ テーブルの説明 ]
１つのデータを新規作成する際に登録する英単語・フレーズの集まり。
| カラム名 | データ型 | 制約 |データの詳細 |
|:-----------|:------------|:------------|:------------|
| note | text |  | 登録する英単語・フレーズに関するメモ |
| user_id | integer |  | このデータを持っているユーザーのID |

## Tagging
[ テーブルの説明 ]
WordAndPhraseとTagテーブルの中間テーブル
| カラム名 | データ型 | 制約 |データの詳細 |
|:-----------|:------------|:------------|:------------|
| word_and_phrase_id | integer | NOT NULL | タグがどのWordAndPhraseに属するか紐づけるためのID |
| tag_id | integer | NOT NULL | WordAndPhraseがどのタグを持つか紐づけるためのID | 

## Tag
[ テーブルの説明 ]
データを新規作成、編集する際に登録するタグ
| カラム名 | データ型 | 制約 |データの詳細 |
|:-----------|:------------|:------------|:------------|
| name | string | NOT NULL | タグにつけられた名前 | 

## WordAndPhraseItem
[ テーブルの説明 ]
各英単語・フレーズ
| カラム名 | データ型 | 制約 |データの詳細 |
|:-----------|:------------|:------------|:------------|
| content | string | NOT NULL | 英単語またはフレーズ |
| explanation | text | NOT NULL | `content`で登録した英単語またはフレーズの意味 |
| word_and_phrase_id | integer | NOT NULL | どのWordAndPhraseに属するかのID |

## Example
[ テーブルの説明 ]
WordAndPhraseItemの`contentカラム`の例文
| カラム名 | データ型 | 制約 |データの詳細 |
|:-----------|:------------|:------------|:------------|
| content | string | NOT NULL | 例文 |
| word_and_phrase_item_id | integer | NOT NULL | どのWordAndPhraseItemに属するか紐づけるためのID |

<details><summary>削除したテーブル</summary>

## WordList 
[ テーブルの説明 ]
データを新規作成した時に属するリスト、ユーザーがログインしデータを操作する前の初期データが入っているリスト、タブ名がWords/Phrasesのリスト。
| カラム名 | データ型 | 制約 | データの詳細 |
|:-----------|:------------|:------------|:------------|
| user_id | integer | | このリストを持っているユーザーのID |

## Quiz
[ テーブルの説明 ]
UserとChoiceの中間テーブル
| カラム名 | データ型 | 制約 |データの詳細 |
|:-----------|:------------|:------------|:------------|
| user_id | integer |  | クイズを実行するユーザーかつデータの所有者 のID|
| choice_id | integer | NOT NULL | 実行されるクイズのリストのID |

## Choice
[ テーブルの説明 ]
どのリストのクイズを実行するかの選択肢
| カラム名 | データ型 | 制約 |データの詳細 |
|:-----------|:------------|:------------|:------------|
| word_list_id | integer | NOT NULL | 選択できるWordListのID |
| bookmark_id | integer |  | 選択できるBookmarkのID |
| memorised_word_id | integer |  | 選択できるMemorisedWordのID |
| word_list | boolean  | NOT NULL, DEFAULT:TRUE | WordListから行うクイズかどうか |
| bookmark | boolean  | NOT NULL, DEFAULT:FALSE | Bookmarkから行うクイズかどうか |
| memorised_word | boolean  | NOT NULL, DEFAULT:FALSE | MemorisedWordから行うクイズかどうか |

## Question
[ テーブルの説明 ]
クイズで出題される質問
| カラム名 | データ型 | 制約 |データの詳細 |
|:-----------|:------------|:------------|:------------|
| quiz_id | integer | NOT NULL | クイズのID |
| question_content_id | integer | NOT NULL | 質問内容 |
| answer_id | integer | NOT NULL | 質問の答え |

## UserAnswer
[ テーブルの説明 ]
ユーザーの回答
| カラム名 | データ型 | 制約 |データの詳細 |
|:-----------|:------------|:------------|:------------|
| question_id | integer | NOT NULL | どの質問に対するユーザーの回答なのか紐づけるためのID |
| user_answer | string |  | ユーザーが入力した回答 |

</details>

# 補足
初期データとして単語・フレーズがいくつか（現在２０語ほどで検討中）登録されているため、ユーザー登録前でもデータの閲覧やそのデータを使用したクイズが可能になっています。
その初期データは私が自前で用意します。
そのため、いくつかの`user_id`の制約はNOT NULLをつけておりません。

**Comment by cafedomancer** [comment]
## 全般

- 各テーブルや各カラムに何のデータが格納されるのかが分かりませんでした。日本語での説明の併記をお願いします。
- 多重度が明記されていない関連があるようです。多重度の追加をお願いします。

## User

- `uid` だけだとログイン中のユーザー情報として表示できるものが何もなさそうです。ログイン中のユーザー情報として何を表示するかをペーパープロトタイピングと合わせて考えてみてください。その上で追加で格納したほうがよい情報があればカラムを追加してください。

**Comment by ai-24** [comment]
## ER図の変更点
### カラム
- Userテーブルにnameカラムを追加
### 多重度
- UserとQuizの多重度でUserを0..1に変更
- UserとWordGroupの多重度でUserを0..1に変更
- UserとWordListの多重度でUserを0..1に変更
- ChoiceとWordListの多重度を追加
- ChoiceとBookmarkの多重度を追加
- ChoiceとMemorisedWordの多重度を追加

**Comment by cafedomancer** [comment]
全体的な懸念点をコメントしてきます。詳しい内容については口頭で会話させてください 🙏 

- テーブル名とカラム名が似ているもしくは同じであるものがいくつかありました。テーブルを指しているのかカラムを指しているのかが曖昧になってしまうので異なるような名前付けを行ったほうがよいかなーと思います。
- 英単語・フレーズの管理は各リスト (`word_lists` と `belong_to_word_list`, `bookmarks` と `belong_to_bookmark`, `memorised_words` と `belong_to_memorised_word`) で管理するのではなく、"ブックマーク" と "覚えた英単語・フレーズ" に関してだけ "ユーザー" と "英単語・フレーズ" の間に中間テーブルのレコードを作成して、その有無でリストに属しているかどうかを判断するのがいいのではないかと思いました。デフォルトのリストと、ブックマーク・覚えた英単語・フレーズのリストは排他になっていると思うのですが、今の管理の方法だと次のような誤ったデータが生まれてしまう可能性があるからです。
  - `word_group(belong_to_word_list: true, belong_to_bookmark: true, belong_to_memorised_word: true)`
- `word_groups` はおそらく英単語・フレーズの新規作成や編集で操作することになるテーブルだと思うのですが、ここの画面の URL は `/words_and_phrases` となっていたはずなので、URL 上のリソースと操作するテーブルが整合していない状態になってしまっている気がします。URL またはテーブル名、もしくはその両方を見直す必要がありそうです。
- `vocabulrary_tags` が `word_groups` と `tags` の間の中間テーブルっぽくない名前なので `taggings` のような分かりやすい名前をつけた方がよさそうです。
- `questions` に保存するデータは `word_groups` に保存するデータの一部 (属性) かなーと思ったのですが、これらが別々のテーブルになっている理由が分かりませんでした。
- `choices` の用途と、どの画面のどの操作で作成・編集・削除されるデータなのかが分かりませんでした。
- ログイン前のユーザーの回答をデータベースに記録するのであれば、それをどう扱うかを考える必要がありそうです。

**Comment by ai-24** [comment]
@cafedomancer 
昨日はお時間いただきありがとうございました。
分かりやすく教えていただいたので理解が進みました！
ご指摘いただいた部分を修正しております。
何か勘違いしている部分があるかもしれません。
再度ご確認よろしくお願いします。

> リレーションの線の両側に多重度が付与されていないものがまだあるので見直してみてください。

words_and_phrasesとword_and_phrase_itemsの多重度と、word_and_phrase_itemsとexamplesの多重度を修正しました。

> テーブル名とカラム名が似ているもしくは同じであるものがいくつかありました。テーブルを指しているのかカラムを指しているのかが曖昧になってしまうので異なるような名前付けを行ったほうがよいかなーと思います。

word_and_phrase_itemsのword_or_phraseとexamplesのexampleをcontentに変更しました。

> 英単語・フレーズの管理は各リスト (word_lists と belong_to_word_list, bookmarks と belong_to_bookmark, memorised_words と belong_to_memorised_word) で管理するのではなく、"ブックマーク" と "覚えた英単語・フレーズ" に関してだけ "ユーザー" と "英単語・フレーズ" の間に中間テーブルのレコードを作成して、その有無でリストに属しているかどうかを判断するのがいいのではないかと思いました。デフォルトのリストと、ブックマーク・覚えた英単語・フレーズのリストは排他になっていると思うのですが、今の管理の方法だと次のような誤ったデータが生まれてしまう可能性があるからです。

中間テーブルを作成し、リレーションも変更しました。

> word_groups はおそらく英単語・フレーズの新規作成や編集で操作することになるテーブルだと思うのですが、ここの画面の URL は /words_and_phrases となっていたはずなので、URL 上のリソースと操作するテーブルが整合していない状態になってしまっている気がします。URL またはテーブル名、もしくはその両方を見直す必要がありそうです。

テーブル名を変更しました。

> vocabulary_tags が word_groups と tags の間の中間テーブルっぽくない名前なので taggings のような分かりやすい名前をつけた方がよさそうです。

taggingsに変更しました。

> questions に保存するデータは words_and_phrases に保存するデータの一部 (属性) かなーと思ったのですが、これらが別々のテーブルになっている理由が分かりませんでした。

いただいたアドバイスを元にword_and_phrase_itemsに`question`と`asnwer`カラムを入れました。

**Comment by cafedomancer** [comment]
- `users` has many `words_and_phrases` の形にすれば `word_lists` は要らないのでは？と思いました。
- 以下の部分の多重度が記載されていなので考えて付けてみてください。
  - `bookmarks` から `users`
  - `memorised_words` から `users`
  - `bookmarks` から `words_and_phrases`
  - `memorised_words` から `words_and_phrases`
  - `taggings` から `words_and_phrases`
  - `taggings` から `tags`
- `bookmarks` や `memorised_words` は `users` と `words_and_phrase` の中間テーブルになり、"ブックマークした" ということや "覚えた" ということを表すテーブルになったので、それに合わせてテーブル名も見直す必要がある気がしました。URL 設計のときのように、統一感のある名前になっているといいんじゃないかなーと思います。
- 確認なのですが、`word_and_phrase_items` の `question` に対する答えは `content` なのかなと思ったのですが、違いますか？ もしそうなのであれば `answer` はいらないのかなと思いました。そうでなければ、`content` と `answer` の違いについて説明していただけると助かります！

**Comment by ai-24** [comment]
@cafedomancer 
レビューありがとうございます。
修正いたしましたのでご確認よろしくお願いいたします。

> users has many words_and_phrases の形にすれば word_lists は要らないのでは？と思いました。

おっしゃる通りでした。ER図からword_lists は削除しました。

> 以下の部分の多重度が記載されていなので考えて付けてみてください。

多重度の付け方の考え方が間違っていたことに気づきました。
ご指摘いただいた部分に全て１の多重度を付けました。

> bookmarks や memorised_words は users と words_and_phrase の中間テーブルになり、"ブックマークした" ということや "覚えた" ということを表すテーブルになったので、それに合わせてテーブル名も見直す必要がある気がしました。URL 設計のときのように、統一感のある名前になっているといいんじゃないかなーと思います。

リソース設計と揃えた名前にしました。

> 確認なのですが、word_and_phrase_items の question に対する答えは content なのかなと思ったのですが、違いますか？ もしそうなのであれば answer はいらないのかなと思いました。そうでなければ、content と answer の違いについて説明していただけると助かります！

question に対する答えは contentなので、answerを削除しました。
questionはexplanationと全く同じ内容なので、questionも削除してしまっても問題ないでしょうか?

**Comment by cafedomancer** [comment]
> > users has many words_and_phrases の形にすれば word_lists は要らないのでは？と思いました。
> 
> おっしゃる通りでした。ER図からword_lists は削除しました。

こちら直っていなさそうです。`words_and_phrases` が `users` に対する参照を持つようになるはずです。

> > 以下の部分の多重度が記載されていなので考えて付けてみてください。
> 
> 多重度の付け方の考え方が間違っていたことに気づきました。 
> ご指摘いただいた部分に全て１の多重度を付けました。

ER 図がもうちょっと変わると思うので、変更が完了したら他重度の方もレビューします。

> > bookmarks や memorised_words は users と words_and_phrase の中間テーブルになり、"ブックマークした" ということや "覚えた" ということを表すテーブルになったので、それに合わせてテーブル名も見直す必要がある気がしました。URL 設計のときのように、統一感のある名前になっているといいんじゃないかなーと思います。
> 
> リソース設計と揃えた名前にしました。

こちらも直っていなさそうです。「"ブックマークした" ということや "覚えた" ということを表すテーブルになったので、それに合わせてテーブル名も見直す必要がある気がしました。」という部分の対応をお願いします。

> > 確認なのですが、word_and_phrase_items の question に対する答えは content なのかなと思ったのですが、違いますか？ もしそうなのであれば answer はいらないのかなと思いました。そうでなければ、content と answer の違いについて説明していただけると助かります！
> 
> question に対する答えは contentなので、answerを削除しました。 questionはexplanationと全く同じ内容なので、questionも削除してしまっても問題ないでしょうか?

そうなんですね！ `question` も削除してしまってよいと思います。

**Comment by ai-24** [comment]
@cafedomancer 
レビューありがとうございます。
修正いたしましたのでご確認よろしくお願いいたします🙇‍♀️

> こちら直っていなさそうです。words_and_phrases が users に対する参照を持つようになるはずです。

失礼いたしました。
リレーションを追加しました。

> ER 図がもうちょっと変わると思うので、変更が完了したら他重度の方もレビューします。

かしこまりました。よろしくお願いいたします。

> こちらも直っていなさそうです。「"ブックマークした" ということや "覚えた" ということを表すテーブルになったので、それに合わせてテーブル名も見直す必要がある気がしました。」という部分の対応をお願いします。

こちらはテーブル名であるbookmarked_words_and_phrasesとmemorised_words_and_phrasesという命名が良くないと認識し、"ブックマークした"をbookmarked、"覚えた"をmemorisedにしました。
テーブル名は名詞の方が良い気もしたので、bookmarksとmemorisationsと迷いましたが、"ブックマークした"、"覚えた" は過去形なのでこのようにしました。認識など間違っている部分がありましたらご指摘お願いします。

> question も削除してしまってよいと思います。

削除しました。

**Comment by cafedomancer** [comment]
## WordAndPhrase

- `user_id` が追加されているはずなので、説明のほうにも `user_id` を追加してください

## WordAndPhraseItem

- `question` が削除されているはずなので、説明のほうでも `question` を削除してください

## Example

- `content` が入っていない例文は意味がないと思うので、`content` には NOT NULL 制約をつけておいたほうがいいかなと思います (いまさらですみません)

## 多重度について

- `users` -> `bookmarked` は、英単語・フレーズがブックマークされていないケースが存在し得るので `0..*` になると思います。`users` -> `memorised`、`words_and_phrases` -> bookmarked`、`words_and_phrases` -> `memorised` についても同様です。
- `words_and_phrases` -> `taggings` は、タグは optional なはずなので `0..*` になると思います。`tags` -> `taggings` についても同様です。

* * *

> こちらはテーブル名であるbookmarked_words_and_phrasesとmemorised_words_and_phrasesという命名が良くないと認識し、"ブックマークした"をbookmarked、"覚えた"をmemorisedにしました。
テーブル名は名詞の方が良い気もしたので、bookmarksとmemorisationsと迷いましたが、"ブックマークした"、"覚えた" は過去形なのでこのようにしました。認識など間違っている部分がありましたらご指摘お願いします。

方針としてはよいと思います。もし名詞形にしたいなら `taggings` のように `bookmarkings` とか `memorisings` とかにするとよいかもしれません。これはお好みで取り入れてください。あとテーブル名は Rails の規約に合わせるなら複数形にしておくとよいと思います。

**Comment by ai-24** [comment]
@cafedomancer 
レビューありがとうございます🙇‍♀️
修正いたしましたので何度も恐れ入りますがご確認よろしくお願いいたします。

## WordAndPhrase
> user_id が追加されているはずなので、説明のほうにも user_id を追加してください


修正が漏れており申し訳ありませんでした。追加いたしました。

## WordAndPhraseItem
> question が削除されているはずなので、説明のほうでも question を削除してください

こちらも修正漏れ失礼いたしました。削除いたしました。

## Example
> content が入っていない例文は意味がないと思うので、content には NOT NULL 制約をつけておいたほうがいいかなと思います (いまさらですみません)

今回いただいたレビューでデータがオプショナルである場合の制約と多重度がよく理解できていなかったことに気づきました。
データがオプショナルであるかどうかは多重度で表し、制約はそのテーブルにカラムとして存在する必要があるかないかということですね。
content に NOT NULL 制約をつけました。

## 多重度について
０以上に修正いたしました。


---

> 方針としてはよいと思います。もし名詞形にしたいなら taggings のように bookmarkings とか memorisings とかにするとよいかもしれません。これはお好みで取り入れてください。あとテーブル名は Rails の規約に合わせるなら複数形にしておくとよいと思います。

なるほどです。
` bookmarkings `と`memorisings`とすることにしました。

**Comment by cafedomancer** [comment]
確認しました。OK です！ 🙆

**Comment by ai-24** [comment]
@cafedomancer 
レビューありがとうございました🙇‍♀️
